export const wishes = [
  "May your day be filled with unexpected moments of joy and laughter.",
  "You are capable of amazing things. Trust in your abilities today.",
  "Every challenge you face is an opportunity to grow stronger and wiser.",
  "Your presence makes the world a better place. Never forget your worth.",
  "Today is a perfect day to start something new and exciting.",
  "You have the power to create positive change in your life and others'.",
  "Embrace the journey, not just the destination. Every step matters.",
  "Your dreams are valid and achievable. Take one step toward them today.",
  "Kindness is never wasted. Spread it generously wherever you go.",
  "You are stronger than you know and more loved than you can imagine.",
  "Today holds endless possibilities. Choose to make it amazing.",
  "Your unique perspective is needed in this world. Share it boldly.",
  "Progress, not perfection, is the key to growth and fulfillment.",
  "You deserve all the happiness and success life has to offer.",
  "Every sunrise brings new chances to shine and make a difference.",
  "Your resilience inspires others. Keep pushing forward with courage.",
  "Small acts of kindness create ripples of positive change.",
  "You are exactly where you need to be. Trust the timing of your life.",
  "Your potential is limitless. Don't be afraid to explore it fully.",
  "Today is a gift. Make the most of every precious moment.",
  "You have survived 100% of your worst days. You can handle today.",
  "Your smile can brighten someone's world. Share it freely.",
  "Success is not final, failure is not fatal. Keep growing and learning.",
  "You are enough, exactly as you are. Never let anyone tell you otherwise.",
  "The world needs your unique talents and perspective. Shine brightly today."
];